# datasource
spring:
  datasource:
    url: jdbc:mysql:///db?serverTimezone=UTC
    username: root
    password: 123.com
    driver-class-name: com.mysql.jdbc.Driver

  dubbo:
      application:
        name: springboot-dubbo-provider #应用名
      registry:
        address: zookeeper://localhost #zookeeper地址
        port: 2181 #提供注册的端口
      protocol:
        name: dubbo
        port: 20890 #dubbo服务暴露的端口
      scan: com.pan.service.impl #扫描的包名

server:
  port: 8080 #Tomcat端口
